# Generated by Django 4.1.2 on 2022-11-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcomunicar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombres'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='zona',
            field=models.CharField(choices=[('Ayacucho', 'Ayacucho'), ('Besote', 'Besote'), ('Contadero', 'Contadero'), ('Costilla', 'Costilla'), ('Empresa', 'Empresa'), ('Julio', 'Julio'), ('La curva', 'La curva'), ('La Esperanza', 'a Esperanza'), ('La Gloria', 'La Gloria'), ('La Mata', 'La Mata'), ('Leon XIII', 'Leon XIII'), ('Molina', 'Molina'), ('Norean', 'Norean'), ('Papayal', 'Papayal'), ('Pate Vaca', 'Pate Vaca'), ('Primavera', 'Primavera'), ('Sabana', 'Sabana'), ('San Alberto', 'San Alberto'), ('San Rafael', 'San Rafael'), ('Simaña', 'Simaña'), ('Tropezon', 'Tropezon'), ('---', '---')], default='---', max_length=15),
        ),
    ]
