zonas = (
        ('Ayacucho', 'Ayacucho'),
        ('Besote', 'Besote'),
        ('Contadero', 'Contadero'),
        ('Costilla', 'Costilla'),
        ('Empresa', 'Empresa'),
        ('Julio', 'Julio'),
        ('La curva', 'La curva'),
        ('La Esperanza', 'a Esperanza'),
        ('La Gloria', 'La Gloria'),
        ('La Mata', 'La Mata'),
        ('Leon XIII', 'Leon XIII'),
        ('Molina', 'Molina'),
        ('Norean', 'Norean'),
        ('Papayal', 'Papayal'),
        ('Pate Vaca', 'Pate Vaca'),
        ('Primavera', 'Primavera'),
        ('Sabana', 'Sabana'),
        ('San Alberto', 'San Alberto'),
        ('San Rafael', 'San Rafael'),
        ('Simaña', 'Simaña'),
        ('Tropezon', 'Tropezon'),
        ('---', '---'),
    )

options = (
        ('activo', 'Activo'),
        ('inactivo', 'Inactivo'),
        ('---', '---'),
    )